#
# Include this before vhost configs...
#
#ifndef acme_config
#define acme_config
 #ifndef acme_root
  #ifdef ca_root
  #define acme_root {ca_root}
  #else
  #define acme_root /root/.acme.sh
  #endif
 #else
  #ifndef ca_root
  #define ca_root {acme_root}
  #endif
 #endif

 #ifndef acme_email
  #ifdef email
   #define acme_email {email}
  #endif
 #endif

 #ifndef acme_get_url
 #define acme_get_url https://get.acme.sh
 #endif
 #ifndef acme_reloadcmd
 #define acme_reloadcmd service apache2 force-reload
 #endif
 #ifndef acme_web_root
 #define acme_web_root /var/www/html
 #endif
 #ifndef acme_server
 #define acme_server letsencrypt.org
 #endif
 #ifndef acme_cron
 #define acme_cron 0 0 * * *
 #endif
 #ifndef acme_issue
 #define acme_issue {acme_root}/acme.sh --issue --server {acme_server} --home {acme_root} -w {acme_web_root}
 #endif

#endif
