#!/usr/bin/python3
'''
This module is used to define constants.  This makes it possible
to catch mispellings.

It is meant to be used for constant values, in particular strings,
used in code.  It is not meant to be used to store user display
strings as these should go into a message catalogue as these
should be translatable to localized strings.

'''

CLOUD = 'CLOUD'
DEFAULT_CLOUD = 'otc'
NAME = 'name'
PROJECT = 'PROJECT'

SID = 'SID'
CONN = 'CONN'
DRYRUN = 'DRYRUN'

stop = 'stop'
start = 'start'
reboot = 'reboot'
status = 'status'
ACTIVE = 'ACTIVE'
SHUTOFF = 'SHUTOFF'
REBOOT = 'REBOOT'
HARD = 'HARD'
SOFT = 'SOFT'

PUBLIC_DNS_ZONE = 'PUBLIC_DNS_ZONE'
CIDR_BLOCK = 'CIDR_BLOCK'
DEFAULT_CIDR_BLOCK = '10.0.0.0/16'
PRIVATE_DNS_ZONE = 'PRIVATE_DNS_ZONE'
DEFAULT_PRIVATE_DNS_ZONE = 'nova.'
DEFAULT_IMAGE = 'DEFAULT_IMAGE'
DEFAULT_IMAGE_VAL = 'Standard_CentOS_8_latest'
DEFAULT_FLAVOR = 'DEFAULT_FLAVOR'
DEFAULT_FLAVOR_VAL = 's3.medium.2'

OS_EXT_IPS_MAC_ADDR = 'OS-EXT-IPS-MAC:mac_addr'
OS_EXT_IPS_TYPE = 'OS-EXT-IPS:type'
sID = 'id'
addresses = 'addresses'
ipv4 = 'ipv4'
mac = 'mac'
nets = 'nets'
vms = 'vms'
vm = 'vm'
addr = 'addr'
flavor = 'flavor'
vcpus = 'vcpus'
ram = 'ram'
flavor_name = 'flavor_name'
original_name = 'original_name'
created_at = 'created_at'
launched_at = 'launched_at'
updated_at = 'updated_at'
vpc = 'vpc'
key = 'key'
public_key = 'public_key'
short_public_key = 'short_public_key'
net = 'net'
subnet_ids = 'subnet_ids'
net_data = 'net_data'
net_name = 'net_name'
net_id = 'net_id'
availability_zones = 'availability_zones'
net_az = 'net_az'
dns_domain = 'dns_domain'
net_dns_domain = 'net_dns_domain'
zone = 'zone'
private = 'private'
public = 'public'
sgs = 'sgs'
vols = 'vols'
vm = 'vm'
vm_device = 'vm_device'
attachments = 'attachments'
server_id = 'server_id'
device = 'device'
location = 'location'
imglst_yaml = 'imglst.yaml'
flavorlst_yaml = 'flavorlst.yaml'
security_group_rules = 'security_group_rules'
rules = 'rules'
image = 'image'
image_id = 'image_id'
image_size = 'image_size'
image_name = 'image_name'
size = 'size'

type = 'type'
CNAME = 'CNAME'
records = 'records'
port_id = 'port_id'

snat = 'snat'
forced_net = 'forced_net'
router_id = 'router_id'

MYOTC_OPTS = 'MYOTC_OPTS'


sn_size = 'sn_size'
USE_OTC_API =  True
