name: generate Windows executables

# on: [push]
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    name: Windows build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Tag versioning
        run: |
          git describe
          python scripts/gitver.py
          python scripts/gitver.py src/version.py
      - name: Install dependencies
        run: |
          del vars.bat
          .\setup.bat
      - name: Package EXEs
        run: |
          .\mk.bat
      - name: Looksie
        run: |
          dir dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
